WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

BALL_SPEED = 100
BALL_SIZE = 3

BLOCK_SIZE = 30
BLOCK_MIN_HEALTH = 50
BLOCK_MAX_HEALTH = 300

NUM_OF_BALLS = 100

ROWS = 10
COLS = 6

START_ROWS = -BLOCK_SIZE * 7
START_COLS = VIRTUAL_WIDTH / 2 - (BLOCK_SIZE * (COLS / 2))

MIN_AIM = 0
MAX_AIM = math.pi
AIM_DIR_RATE_OF_CHANGE = math.pi / 2

LINE_LENGTH = 50